SELECT `type_id`, `type_name`, `one_id`, `one_name`, `two_id`, `two_name`, `three_id`, `three_name`, `four_id`, `four_name`, `create_time`, `create_user`, `update_time`, `update_user`
FROM data_dictionary
WHERE type_id in (
    'CASHIER_ACCOUNT_BANK_NAME',
    'CASHIER_BANK_ACCOUNT_TYPE',
    'CASHIER_TAX_AGREEMENT_STATUS',
    'CASHIER_CANCEL_STATUS_OPTIONS',
    'CASHIER_DEPARTMENT_PROPERTIES',
    'CASHIER_SEAL_STATUS_OPTIONS',
    'CASHIER_GUARANTEE_RETURN_STATUS_OPTIONS',
    'CASHIER_CAN_CLOSE_STORE_OPTIONS',
    'CASHIER_COMPANY_STATUS',
    'CASHIER_COMPANY_ATTRIBUTION_TYPE',
    'CASHIER_TAXPAYER_TYPE',
    'CASHIER_TAX_STATUS',
    'CASHIER_BUSINESS_STATUS',
    'CASHIER_ARCHIVE_STATUS',
    'CASHIER_TAX_PERIOD',
    'CASHIER_ACCOUNTING_COMPANY',
    'TAX_TYPE_OPTIONS',
    'DOMESTIC_PROVINCE_OPTIONS',
    'FOREIGN_COUNTRY_OPTIONS'
)